### ISSUE TITLE
Fehlende SSL-Verschlüsselung der Api

### ISSUE THREAD

**Issue by sebastianbroc** [sebastianbroc/P2_Barrierefreiheit_ECommerce#6]
Momentan ist die API nur via HTTP erreichbar. Ohne dies in Chrome manuell zuzulassen, würden die API-Anfragen deshalb aus Sicherheitsgründen garnicht rausgehen. Die API muss zwingend eine SSL-Verschlüsselung erhalten.

<img width="1440" alt="Bildschirmfoto 2023-06-06 um 18 25 06" src="https://github.com/sebastianbroc/P2_Barrierefreiheit_ECommerce/assets/63352229/634937fd-3e45-42c7-854b-8efd0fbd8d55">

**Comment by Taha-Moujtahid** [comment]
Fehler behoben! Api kann nun über https://api.burnoutstud.io/ bzw https://api.burnoutstud.io/swagger/index.html aufgerufen werden.
